version: 0.2

phases:
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t assignment5 .
      - echo "Tagging Docker image..."
      - docker tag assignment5 public.ecr.aws/t5k9x2g4/assignment5:ver1
  
  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push public.ecr.aws/t5k9x2g4/assignment5:ver1

artifacts:
  files: []
