version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin public.ecr.aws/t5k9x2g4
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t assignment5 .
      - echo "Tagging Docker image..."
      - docker tag assignment5 public.ecr.aws/t5k9x2g4/assignment5:ver1
  
  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push public.ecr.aws/t5k9x2g4/assignment5:ver1

artifacts:
  files: []
